const State = {
          roomType: "BATTLE",
          gold: 0,
          player: {
            x: 1,
            y: 1,
            hp: 100,
            maxHp: 100,
            abilities: [],
            shields: 0,
            effects: [],
            pages: 0,
            class: "-",
            armor: null,
            armorMods: {},
            talents: {},
            spriteSet: null,
            movingTicks: 0,
          },
          enemies: [],
          turn: "PLAYER",
          selection: null,
          floor: 1,
          stage: 0,
          stageFloor: 1,
          storyIndex: 0,
          extraActions: 0,
        };

        // ========= classes / talents =========
